### ISSUE TITLE
bootstrapping with an ssh key

### ISSUE THREAD

**Issue by joelgordon** [uyuni-project/uyuni-docs#386]
We do not use SSH passwords anywhere. Since most of our servers are publicly available we only use SSH key based authentication. This is not an issue since we found the ssh key that we needed and added it to our servers. We had to bootstrap a test server and then grep for the SSh key on the SuMa file system. This is not a documented procedure, but I believe it should be. The key that was needed to bootstrap our server was in [1]. After adding this key to the bootstrap users authorized_keys, we were able to bootstrap without using a password. This was with both the web-ui and the xml-rpc api. The documentation should be attached to both bootstrapping methods. 

[1] /srv/susemanager/salt/salt_ssh/mgr_ssh_id.pub

**Comment by juliogonzalez** [comment]
To bootstrap without password you need to give the private key that allow access to the client. This is documented for the WebUI: https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/reference/systems/bootstrapping.html

And it's at the API doc: https://documentation.suse.com/external-tree/en-us/suma/4.1/pdf/susemanager_api_doc_color_en.pdf `44.6 bootstrapWithPrivateSshKey`

(and for Uyuni as well on the equivalent URLs).

Unless I am very wrong, that key you found is only used to manage Salt SSH minions after the bootstrap, but should not be used to do the bootstrap itself for any kind of client, and AFAIK that's why this is not documented.

What the feature I described on the links above applies to SUSE Manager >=4.1 and Uyuni  >= 2020.04

For previous versions of SUSE Manager or Uyuni, this feature is not available.

**Comment by joelgordon** [comment]
We are using SuMa 4.0 and I do not see a way to specify a key instead of a password in the web ui.

**Comment by juliogonzalez** [comment]
No, you can't.

Using private keys from WebUI and XMLRPC is only supported on SUSE Manager >= 4.1

To be in 4.0, this feature would require a backport. Please write to the internal mailing list so it can be discussed there.

**Comment by mcalmer** [comment]
It was not planned that it works, but it make sense. AFAIK ssh try first with the key in its home and this is our management ssh key. Normally it is not possible to use it as it is not setup and then it fallback to the password.

With 4.1 it might not work anymore, because you can specify a 1 time key for bootstrapping.

**Comment by joelgordon** [comment]
Ok, Since this changes in 4.1, I will close this issue for now, and we will continue to use this method for our own bootstrapping. When we migrate to 4.1 we will change the method to the supported temporary key based method.
